# Generated by Django 3.1.5 on 2021-01-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='pokemon_id',
            new_name='pokemon',
        ),
    ]
