# Generated by Django 3.1.5 on 2021-01-10 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonapp', '0002_auto_20210109_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='evolves_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_to', to='pokemonapp.pokemon'),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='pokemon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_from', to='pokemonapp.pokemon'),
        ),
    ]
