# Generated by Django 3.1.5 on 2021-01-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonapp', '0004_auto_20210110_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='evolves_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution', to='pokemonapp.pokemon'),
        ),
    ]
